spring:
  application:
    name: ling-long
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ling_long
    username: postgres
    password: postgres
jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  database-validation:
    mode: ERROR
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  executor-context-prefixes:
    - com.bingo.linglong
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: LingLong Web Service
          description: |
            LingLong 后台管理系统
          version: 1.0
    ts:
      path: /ts.zip
sa-token:
  token-name: Authorization